package com.CampusMall.Pojo;

public class AdminType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_type.atype_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private Long atypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_type.atype_name
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private String atypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_type.atype_id
     *
     * @return the value of t_admin_type.atype_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public Long getAtypeId() {
        return atypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_type.atype_id
     *
     * @param atypeId the value for t_admin_type.atype_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setAtypeId(Long atypeId) {
        this.atypeId = atypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_type.atype_name
     *
     * @return the value of t_admin_type.atype_name
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getAtypeName() {
        return atypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_type.atype_name
     *
     * @param atypeName the value for t_admin_type.atype_name
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setAtypeName(String atypeName) {
        this.atypeName = atypeName == null ? null : atypeName.trim();
    }
}