package com.CampusMall.Pojo;

import java.util.ArrayList;
import java.util.List;

public class AdminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public AdminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaIdIsNull() {
            addCriterion("ta_id is null");
            return (Criteria) this;
        }

        public Criteria andTaIdIsNotNull() {
            addCriterion("ta_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaIdEqualTo(Long value) {
            addCriterion("ta_id =", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdNotEqualTo(Long value) {
            addCriterion("ta_id <>", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdGreaterThan(Long value) {
            addCriterion("ta_id >", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ta_id >=", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdLessThan(Long value) {
            addCriterion("ta_id <", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdLessThanOrEqualTo(Long value) {
            addCriterion("ta_id <=", value, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdIn(List<Long> values) {
            addCriterion("ta_id in", values, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdNotIn(List<Long> values) {
            addCriterion("ta_id not in", values, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdBetween(Long value1, Long value2) {
            addCriterion("ta_id between", value1, value2, "taId");
            return (Criteria) this;
        }

        public Criteria andTaIdNotBetween(Long value1, Long value2) {
            addCriterion("ta_id not between", value1, value2, "taId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("admin_id is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("admin_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(String value) {
            addCriterion("admin_id =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(String value) {
            addCriterion("admin_id <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(String value) {
            addCriterion("admin_id >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(String value) {
            addCriterion("admin_id >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(String value) {
            addCriterion("admin_id <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(String value) {
            addCriterion("admin_id <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLike(String value) {
            addCriterion("admin_id like", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotLike(String value) {
            addCriterion("admin_id not like", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<String> values) {
            addCriterion("admin_id in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<String> values) {
            addCriterion("admin_id not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(String value1, String value2) {
            addCriterion("admin_id between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(String value1, String value2) {
            addCriterion("admin_id not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNull() {
            addCriterion("admin_name is null");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNotNull() {
            addCriterion("admin_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdminNameEqualTo(String value) {
            addCriterion("admin_name =", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotEqualTo(String value) {
            addCriterion("admin_name <>", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThan(String value) {
            addCriterion("admin_name >", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThanOrEqualTo(String value) {
            addCriterion("admin_name >=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThan(String value) {
            addCriterion("admin_name <", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThanOrEqualTo(String value) {
            addCriterion("admin_name <=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLike(String value) {
            addCriterion("admin_name like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotLike(String value) {
            addCriterion("admin_name not like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameIn(List<String> values) {
            addCriterion("admin_name in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotIn(List<String> values) {
            addCriterion("admin_name not in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameBetween(String value1, String value2) {
            addCriterion("admin_name between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotBetween(String value1, String value2) {
            addCriterion("admin_name not between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIsNull() {
            addCriterion("admin_password is null");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIsNotNull() {
            addCriterion("admin_password is not null");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordEqualTo(String value) {
            addCriterion("admin_password =", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotEqualTo(String value) {
            addCriterion("admin_password <>", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordGreaterThan(String value) {
            addCriterion("admin_password >", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("admin_password >=", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLessThan(String value) {
            addCriterion("admin_password <", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLessThanOrEqualTo(String value) {
            addCriterion("admin_password <=", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLike(String value) {
            addCriterion("admin_password like", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotLike(String value) {
            addCriterion("admin_password not like", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIn(List<String> values) {
            addCriterion("admin_password in", values, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotIn(List<String> values) {
            addCriterion("admin_password not in", values, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordBetween(String value1, String value2) {
            addCriterion("admin_password between", value1, value2, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotBetween(String value1, String value2) {
            addCriterion("admin_password not between", value1, value2, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminForbidIsNull() {
            addCriterion("admin_forbid is null");
            return (Criteria) this;
        }

        public Criteria andAdminForbidIsNotNull() {
            addCriterion("admin_forbid is not null");
            return (Criteria) this;
        }

        public Criteria andAdminForbidEqualTo(Boolean value) {
            addCriterion("admin_forbid =", value, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidNotEqualTo(Boolean value) {
            addCriterion("admin_forbid <>", value, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidGreaterThan(Boolean value) {
            addCriterion("admin_forbid >", value, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("admin_forbid >=", value, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidLessThan(Boolean value) {
            addCriterion("admin_forbid <", value, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidLessThanOrEqualTo(Boolean value) {
            addCriterion("admin_forbid <=", value, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidIn(List<Boolean> values) {
            addCriterion("admin_forbid in", values, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidNotIn(List<Boolean> values) {
            addCriterion("admin_forbid not in", values, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidBetween(Boolean value1, Boolean value2) {
            addCriterion("admin_forbid between", value1, value2, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAdminForbidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("admin_forbid not between", value1, value2, "adminForbid");
            return (Criteria) this;
        }

        public Criteria andAtypeIdIsNull() {
            addCriterion("atype_id is null");
            return (Criteria) this;
        }

        public Criteria andAtypeIdIsNotNull() {
            addCriterion("atype_id is not null");
            return (Criteria) this;
        }

        public Criteria andAtypeIdEqualTo(String value) {
            addCriterion("atype_id =", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdNotEqualTo(String value) {
            addCriterion("atype_id <>", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdGreaterThan(String value) {
            addCriterion("atype_id >", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("atype_id >=", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdLessThan(String value) {
            addCriterion("atype_id <", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdLessThanOrEqualTo(String value) {
            addCriterion("atype_id <=", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdLike(String value) {
            addCriterion("atype_id like", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdNotLike(String value) {
            addCriterion("atype_id not like", value, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdIn(List<String> values) {
            addCriterion("atype_id in", values, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdNotIn(List<String> values) {
            addCriterion("atype_id not in", values, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdBetween(String value1, String value2) {
            addCriterion("atype_id between", value1, value2, "atypeId");
            return (Criteria) this;
        }

        public Criteria andAtypeIdNotBetween(String value1, String value2) {
            addCriterion("atype_id not between", value1, value2, "atypeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbggenerated do_not_delete_during_merge Fri May 26 14:11:52 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}