package com.CampusMall.Pojo;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.ta_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private Long taId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private String adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_name
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_password
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_forbid
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private Boolean adminForbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.atype_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private String atypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.ta_id
     *
     * @return the value of t_admin.ta_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public Long getTaId() {
        return taId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.ta_id
     *
     * @param taId the value for t_admin.ta_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setTaId(Long taId) {
        this.taId = taId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_id
     *
     * @return the value of t_admin.admin_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_id
     *
     * @param adminId the value for t_admin.admin_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_name
     *
     * @return the value of t_admin.admin_name
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_name
     *
     * @param adminName the value for t_admin.admin_name
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_password
     *
     * @return the value of t_admin.admin_password
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_password
     *
     * @param adminPassword the value for t_admin.admin_password
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_forbid
     *
     * @return the value of t_admin.admin_forbid
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public Boolean getAdminForbid() {
        return adminForbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_forbid
     *
     * @param adminForbid the value for t_admin.admin_forbid
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setAdminForbid(Boolean adminForbid) {
        this.adminForbid = adminForbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.atype_id
     *
     * @return the value of t_admin.atype_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getAtypeId() {
        return atypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.atype_id
     *
     * @param atypeId the value for t_admin.atype_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setAtypeId(String atypeId) {
        this.atypeId = atypeId == null ? null : atypeId.trim();
    }
}