package com.CampusMall.Pojo;

public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.tc_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    private Long tcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.cart_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    private String cartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.user_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.p_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.p_count
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    private Long pCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.p_price
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    private Long pPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.p_name
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    private String pName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.tc_id
     *
     * @return the value of t_cart.tc_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public Long getTcId() {
        return tcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.tc_id
     *
     * @param tcId the value for t_cart.tc_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public void setTcId(Long tcId) {
        this.tcId = tcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.cart_id
     *
     * @return the value of t_cart.cart_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public String getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.cart_id
     *
     * @param cartId the value for t_cart.cart_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public void setCartId(String cartId) {
        this.cartId = cartId == null ? null : cartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.user_id
     *
     * @return the value of t_cart.user_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.user_id
     *
     * @param userId the value for t_cart.user_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.p_id
     *
     * @return the value of t_cart.p_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.p_id
     *
     * @param pId the value for t_cart.p_id
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.p_count
     *
     * @return the value of t_cart.p_count
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public Long getpCount() {
        return pCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.p_count
     *
     * @param pCount the value for t_cart.p_count
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public void setpCount(Long pCount) {
        this.pCount = pCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.p_price
     *
     * @return the value of t_cart.p_price
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public Long getpPrice() {
        return pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.p_price
     *
     * @param pPrice the value for t_cart.p_price
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public void setpPrice(Long pPrice) {
        this.pPrice = pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.p_name
     *
     * @return the value of t_cart.p_name
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.p_name
     *
     * @param pName the value for t_cart.p_name
     *
     * @mbggenerated Tue May 30 06:52:35 CST 2023
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }
}