package com.CampusMall.Pojo;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.toi_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private Long toiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.order_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.pro_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private String proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.p_count
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    private Long pCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.toi_id
     *
     * @return the value of t_order_info.toi_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public Long getToiId() {
        return toiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.toi_id
     *
     * @param toiId the value for t_order_info.toi_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setToiId(Long toiId) {
        this.toiId = toiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.order_id
     *
     * @return the value of t_order_info.order_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.order_id
     *
     * @param orderId the value for t_order_info.order_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.pro_id
     *
     * @return the value of t_order_info.pro_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.pro_id
     *
     * @param proId the value for t_order_info.pro_id
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.p_count
     *
     * @return the value of t_order_info.p_count
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public Long getpCount() {
        return pCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.p_count
     *
     * @param pCount the value for t_order_info.p_count
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    public void setpCount(Long pCount) {
        this.pCount = pCount;
    }
}