package com.CampusMall.Pojo;

public class ProductType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.ptt_id
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    private Long pttId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.type_name
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.type_id
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    private String typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.ptt_id
     *
     * @return the value of t_product_type.ptt_id
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    public Long getPttId() {
        return pttId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.ptt_id
     *
     * @param pttId the value for t_product_type.ptt_id
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    public void setPttId(Long pttId) {
        this.pttId = pttId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.type_name
     *
     * @return the value of t_product_type.type_name
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.type_name
     *
     * @param typeName the value for t_product_type.type_name
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.type_id
     *
     * @return the value of t_product_type.type_id
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.type_id
     *
     * @param typeId the value for t_product_type.type_id
     *
     * @mbggenerated Mon May 29 15:48:29 CST 2023
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }
}