package com.CampusMall.Pojo;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.tp_id
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    private Long tpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.p_id
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.p_name
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.p_price
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    private Long pPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.p_img
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    private String pImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.p_type
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    private String pType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.p_num
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    private Long pNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.tp_id
     *
     * @return the value of t_product.tp_id
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public Long getTpId() {
        return tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.tp_id
     *
     * @param tpId the value for t_product.tp_id
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public void setTpId(Long tpId) {
        this.tpId = tpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.p_id
     *
     * @return the value of t_product.p_id
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.p_id
     *
     * @param pId the value for t_product.p_id
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.p_name
     *
     * @return the value of t_product.p_name
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.p_name
     *
     * @param pName the value for t_product.p_name
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.p_price
     *
     * @return the value of t_product.p_price
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public Long getpPrice() {
        return pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.p_price
     *
     * @param pPrice the value for t_product.p_price
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public void setpPrice(Long pPrice) {
        this.pPrice = pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.p_img
     *
     * @return the value of t_product.p_img
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public String getpImg() {
        return pImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.p_img
     *
     * @param pImg the value for t_product.p_img
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public void setpImg(String pImg) {
        this.pImg = pImg == null ? null : pImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.p_type
     *
     * @return the value of t_product.p_type
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public String getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.p_type
     *
     * @param pType the value for t_product.p_type
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public void setpType(String pType) {
        this.pType = pType == null ? null : pType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.p_num
     *
     * @return the value of t_product.p_num
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public Long getpNum() {
        return pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.p_num
     *
     * @param pNum the value for t_product.p_num
     *
     * @mbggenerated Mon May 29 14:19:52 CST 2023
     */
    public void setpNum(Long pNum) {
        this.pNum = pNum;
    }
}