package com.CampusMall.Pojo;

public class TB {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_by.id
     *
     * @mbggenerated Wed May 31 21:46:48 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_by.B
     *
     * @mbggenerated Wed May 31 21:46:48 CST 2023
     */
    private byte[] b;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_by.id
     *
     * @return the value of t_by.id
     *
     * @mbggenerated Wed May 31 21:46:48 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_by.id
     *
     * @param id the value for t_by.id
     *
     * @mbggenerated Wed May 31 21:46:48 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_by.B
     *
     * @return the value of t_by.B
     *
     * @mbggenerated Wed May 31 21:46:48 CST 2023
     */
    public byte[] getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_by.B
     *
     * @param b the value for t_by.B
     *
     * @mbggenerated Wed May 31 21:46:48 CST 2023
     */
    public void setB(byte[] b) {
        this.b = b;
    }
}