package com.CampusMall.Pojo;

public class UserSearch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.tus_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private Long tusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.user_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.p_name
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.p_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.p_price
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private Long pPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.p_img
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private String pImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.p_num
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private Long pNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.usersearch_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private String usersearchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_search.p_type
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    private String pType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.tus_id
     *
     * @return the value of t_user_search.tus_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public Long getTusId() {
        return tusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.tus_id
     *
     * @param tusId the value for t_user_search.tus_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setTusId(Long tusId) {
        this.tusId = tusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.user_id
     *
     * @return the value of t_user_search.user_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.user_id
     *
     * @param userId the value for t_user_search.user_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.p_name
     *
     * @return the value of t_user_search.p_name
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.p_name
     *
     * @param pName the value for t_user_search.p_name
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.p_id
     *
     * @return the value of t_user_search.p_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.p_id
     *
     * @param pId the value for t_user_search.p_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.p_price
     *
     * @return the value of t_user_search.p_price
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public Long getpPrice() {
        return pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.p_price
     *
     * @param pPrice the value for t_user_search.p_price
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setpPrice(Long pPrice) {
        this.pPrice = pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.p_img
     *
     * @return the value of t_user_search.p_img
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public String getpImg() {
        return pImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.p_img
     *
     * @param pImg the value for t_user_search.p_img
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setpImg(String pImg) {
        this.pImg = pImg == null ? null : pImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.p_num
     *
     * @return the value of t_user_search.p_num
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public Long getpNum() {
        return pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.p_num
     *
     * @param pNum the value for t_user_search.p_num
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setpNum(Long pNum) {
        this.pNum = pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.usersearch_id
     *
     * @return the value of t_user_search.usersearch_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public String getUsersearchId() {
        return usersearchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.usersearch_id
     *
     * @param usersearchId the value for t_user_search.usersearch_id
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setUsersearchId(String usersearchId) {
        this.usersearchId = usersearchId == null ? null : usersearchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_search.p_type
     *
     * @return the value of t_user_search.p_type
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public String getpType() {
        return pType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_search.p_type
     *
     * @param pType the value for t_user_search.p_type
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    public void setpType(String pType) {
        this.pType = pType == null ? null : pType.trim();
    }
}