package com.CampusMall.Mapper;

import com.CampusMall.Pojo.AdminType;
import com.CampusMall.Pojo.AdminTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int countByExample(AdminTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int deleteByExample(AdminTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int deleteByPrimaryKey(Long atypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int insert(AdminType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int insertSelective(AdminType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    List<AdminType> selectByExample(AdminTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    AdminType selectByPrimaryKey(Long atypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int updateByExampleSelective(@Param("record") AdminType record, @Param("example") AdminTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int updateByExample(@Param("record") AdminType record, @Param("example") AdminTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int updateByPrimaryKeySelective(AdminType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_type
     *
     * @mbggenerated Fri May 26 14:11:52 CST 2023
     */
    int updateByPrimaryKey(AdminType record);
}