package com.CampusMall.Mapper;

import com.CampusMall.Pojo.OrderComplete;
import com.CampusMall.Pojo.OrderCompleteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderCompleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int countByExample(OrderCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int deleteByExample(OrderCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int deleteByPrimaryKey(Long toId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int insert(OrderComplete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int insertSelective(OrderComplete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    List<OrderComplete> selectByExample(OrderCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    OrderComplete selectByPrimaryKey(Long toId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int updateByExampleSelective(@Param("record") OrderComplete record, @Param("example") OrderCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int updateByExample(@Param("record") OrderComplete record, @Param("example") OrderCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int updateByPrimaryKeySelective(OrderComplete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complete
     *
     * @mbggenerated Tue May 30 21:05:08 CST 2023
     */
    int updateByPrimaryKey(OrderComplete record);
}