package com.CampusMall.Mapper;

import com.CampusMall.Pojo.UserSearch;
import com.CampusMall.Pojo.UserSearchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int countByExample(UserSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int deleteByExample(UserSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int deleteByPrimaryKey(Long tusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int insert(UserSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int insertSelective(UserSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    List<UserSearch> selectByExample(UserSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    UserSearch selectByPrimaryKey(Long tusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") UserSearch record, @Param("example") UserSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int updateByExample(@Param("record") UserSearch record, @Param("example") UserSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int updateByPrimaryKeySelective(UserSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_search
     *
     * @mbggenerated Mon May 29 17:37:42 CST 2023
     */
    int updateByPrimaryKey(UserSearch record);
}